---
Name: nswdpc-field-hint
---
SilverStripe\Forms\FormAction:
  extensions:
    - 'NSWPDC\FieldHint\Extensions\Hintable'
SilverStripe\Forms\CompositeField:
  extensions:
    - 'NSWPDC\FieldHint\Extensions\Hintable'
SilverStripe\Forms\HTMLReadonlyField:
  extensions:
    - 'NSWPDC\FieldHint\Extensions\Hintable'
SilverStripe\Forms\FormField:
  hint_class_mapping: []
